/*
========================================
Magnitude Analysis
========================================
Purpose:
	- To quantify data and group results by specific dimensions.
	- For understanding data distribution across categories.
*/
-- find the total customers by city
select city_name, count(customer_id) as total_customers
from  gold.dim_customers
group by city_name
order by total_customers desc;

-- find the total employees by city
select city_name, count(employee_id) as total_employees
from  gold.dim_employees
group by city_name
order by total_employees desc;

-- what is the total sales generated by each city
select dc.city_name, sum(fs.total_price)as total_sales
from gold.fact_sales fs
left join gold.dim_customers dc 
on fs.customer_id=dc.customer_id 
group by dc.city_name
order by total_sales desc;

-- what is the total product sold by city
select dc.city_name, sum(fs.quantity)as quantity
from gold.fact_sales fs
left join gold.dim_customers dc 
on fs.customer_id=dc.customer_id 
group by dc.city_name
order by quantity desc;


-- find the total transaction by city
select dc.city_name, count(sales_id) as total_transactions
from gold.fact_sales fs
left join gold.dim_customers dc 
on fs.customer_id=dc.customer_id 
group by dc.city_name
order by total_transactions desc;

--  find total product by class 
select class, count(product_id) as total_products
from gold.dim_products
group by class
order by total_products desc;

-- what is averaage vitality days by class
select class, avg(vitality_days) as average_vitality_days
from gold.dim_products
group by class
order by average_vitality_days desc;

-- find the total product by resistant
select resistant, count(product_id) as total_products
from gold.dim_products
group by resistant
order by total_products desc;

-- find the total product by product category
select category_name, count(product_id) as total_products
from gold.dim_products
group by category_name 
order by total_products desc;

-- what is the total sales generated by each product category
select dp.category_name, sum(fs.total_price) as total_sales
from gold.fact_sales fs
left join gold.dim_products dp
on fs.product_id=dp.product_id
group by dp.category_name
order by total_sales desc;

-- find the average sales per product category
select dp.category_name, avg(fs.total_price) as average_sales
from gold.fact_sales fs
left join gold.dim_products dp 
on fs.product_id=dp.product_id
group by dp.category_name 
order by average_sales desc;

-- find the total quantity per product category
select dp.category_name, sum(fs.quantity) as total_quantity
from gold.fact_sales fs
left join gold.dim_products dp 
on fs.product_id=dp.product_id
group by dp.category_name 
order by total_quantity desc;

-- find total transaction per product category
select dp.category_name, count(sales_id) as total_transactions
from gold.fact_sales fs
left join gold.dim_products dp 
on fs.product_id=dp.product_id
group by dp.category_name 
order by total_transactions desc;

-- find the total employees by gender
select gender, count(employee_id) as total_employees
from gold.dim_employees
group by gender 
order by total_employees desc;

-- Get total transactions processed by each gender
select de.gender, count(fs.sales_id) as total_transactions
from gold.fact_sales fs
left join gold.dim_employees de 
on fs.employee_id=de.employee_id 
group by de.gender
order by total_transactions;

-- Get total transactions processed by each employee
select de.employee_name, count(fs.sales_id) as total_transactions
from gold.fact_sales fs
left join gold.dim_employees de 
on fs.employee_id=de.employee_id 
group by de.employee_name
order by total_transactions desc;

-- what is the total sales generated by each customer
select dc.customer_name, sum(fs.total_price) as total_sales
from gold.fact_sales fs
left join gold.dim_customers dc 
on fs.customer_id =dc.customer_id 
group by customer_name 
order by total_sales desc;

-- what is the total transaction generated by each customer
select dc.customer_name, count(fs.sales_id) as total_transactions
from gold.fact_sales fs
left join gold.dim_customers dc 
on fs.customer_id =dc.customer_id 
group by customer_name 
order by total_transactions desc;
